### ISSUE TITLE
Support for external_uid?

### ISSUE THREAD

**Issue by jenkin** [PyBossa/pybossa.js#34]
PyBOSSA API supports external_uid for the `newtask` and `taskrun` endpoints (see [api/task/external/](http://docs.pybossa.com/api/task/external/)). How can I use this feature using the js library? I could not find informations about that in the documentation or inside the code, except for a reference in the [getting a task](http://pybossajs.readthedocs.io/en/latest/library.html#getting-a-task) page: "when a task is submitted by an authenticated user, the task will save his user_id". Thank you!

**Comment by teleyinex** [comment]
Hi,

This is not implemented in the library. Please, feel free to send a pull request with this functionality if you need it. We have not implemented it, because it's really easy to do it using libraries like axios or jQuery. Also, this feature was basically implemented for Android and iOS apps, so they will use their own libraries for this feature.

All the best,

Daniel
